apiVersion: apps/v1
kind: Deployment
metadata:
  name: valax-rtp
  namespace: valax
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  valax-rtp
  template:
    metadata:
      labels:
        app:  valax-rtp
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name:  valax-rtp
        image: valax0301.jfrog.io/valaxy-docker/ttrend:2.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        