apiVersion: v1
kind: Service
metadata:
  name:  valax-rtp-service
  namespace: valax
spec:
  type: LoadBalancer
  selector:
    app: valax-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000